export const advertisementsCars = [
    {
      id: "1",
      title: "Porsche - 718",
      description: "Product title stays here - maximum 1 line",
      owner: "Christian",
      km: "0",
      year: "2019",
      price: "00.000,00",
      image:
        "https://primeveiculosbh.com.br/wp-content/uploads/2023/01/718-Cayman-2.0-Turbo-Gasolina-Automatico-Prata-2019-Porsche-Lateral-Frente-Lado-Esquerdo-Prime-Veiculos-BH-Belo-Horizonte-MG.jpeg",
      isGoodBuy: false,
      isActive: true,
      isHomePage: true,
      isLarge: false,
    },
    {
      id: "2",
      title: "Porsche - 718",
      description: "Product title stays here - maximum 1 line",
      owner: "Christian",
      km: "0",
      year: "2019",
      price: "00.000,00",
      image:
        "https://primeveiculosbh.com.br/wp-content/uploads/2023/01/718-Cayman-2.0-Turbo-Gasolina-Automatico-Prata-2019-Porsche-Lateral-Frente-Lado-Esquerdo-Prime-Veiculos-BH-Belo-Horizonte-MG.jpeg",
      isGoodBuy: true,
      isActive: true,
      isHomePage: true,
      isLarge: false,
    },
    {
      id: "3",
      title: "Porsche - 718",
      description: "Product title stays here - maximum 1 line",
      owner: "Christian",
      km: "0",
      year: "2019",
      price: "00.000,00",
      image:
        "https://primeveiculosbh.com.br/wp-content/uploads/2023/01/718-Cayman-2.0-Turbo-Gasolina-Automatico-Prata-2019-Porsche-Lateral-Frente-Lado-Esquerdo-Prime-Veiculos-BH-Belo-Horizonte-MG.jpeg",
      isGoodBuy: false,
      isActive: true,
      isHomePage: true,
      isLarge: false,
    },
    {
      id: "4",
      title: "Porsche - 718",
      description: "Product title stays here - maximum 1 line",
      owner: "Christian",
      km: "0",
      year: "2019",
      price: "00.000,00",
      image:
        "https://primeveiculosbh.com.br/wp-content/uploads/2023/01/718-Cayman-2.0-Turbo-Gasolina-Automatico-Prata-2019-Porsche-Lateral-Frente-Lado-Esquerdo-Prime-Veiculos-BH-Belo-Horizonte-MG.jpeg",
      isGoodBuy: true,
      isActive: true,
      isHomePage: true,
      isLarge: false,
    },
    {
      id: "5",
      title: "Porsche - 718",
      description: "Product title stays here - maximum 1 line",
      owner: "Christian",
      km: "0",
      year: "2019",
      price: "00.000,00",
      image:
        "https://primeveiculosbh.com.br/wp-content/uploads/2023/01/718-Cayman-2.0-Turbo-Gasolina-Automatico-Prata-2019-Porsche-Lateral-Frente-Lado-Esquerdo-Prime-Veiculos-BH-Belo-Horizonte-MG.jpeg",
      isGoodBuy: false,
      isActive: true,
      isHomePage: true,
      isLarge: false,
    },
    {
      id: "6",
      title: "Porsche - 718",
      description: "Product title stays here - maximum 1 line",
      owner: "Christian",
      km: "0",
      year: "2019",
      price: "00.000,00",
      image:
        "https://primeveiculosbh.com.br/wp-content/uploads/2023/01/718-Cayman-2.0-Turbo-Gasolina-Automatico-Prata-2019-Porsche-Lateral-Frente-Lado-Esquerdo-Prime-Veiculos-BH-Belo-Horizonte-MG.jpeg",
      isGoodBuy: false,
      isActive: true,
      isHomePage: true,
      isLarge: false,
    },
    {
        id: "7",
        title: "Porsche - 718",
        description: "Product title stays here - maximum 1 line",
        owner: "Christian",
        km: "0",
        year: "2019",
        price: "00.000,00",
        image:
          "https://primeveiculosbh.com.br/wp-content/uploads/2023/01/718-Cayman-2.0-Turbo-Gasolina-Automatico-Prata-2019-Porsche-Lateral-Frente-Lado-Esquerdo-Prime-Veiculos-BH-Belo-Horizonte-MG.jpeg",
        isGoodBuy: false,
        isActive: true,
        isHomePage: true,
        isLarge: false,
      },
      {
        id: "8",
        title: "Porsche - 718",
        description: "Product title stays here - maximum 1 line",
        owner: "Christian",
        km: "0",
        year: "2019",
        price: "00.000,00",
        image:
          "https://primeveiculosbh.com.br/wp-content/uploads/2023/01/718-Cayman-2.0-Turbo-Gasolina-Automatico-Prata-2019-Porsche-Lateral-Frente-Lado-Esquerdo-Prime-Veiculos-BH-Belo-Horizonte-MG.jpeg",
        isGoodBuy: false,
        isActive: true,
        isHomePage: true,
        isLarge: false,
      },
      {
        id: "9",
        title: "Porsche - 718",
        description: "Product title stays here - maximum 1 line",
        owner: "Christian",
        km: "0",
        year: "2019",
        price: "00.000,00",
        image:
          "https://primeveiculosbh.com.br/wp-content/uploads/2023/01/718-Cayman-2.0-Turbo-Gasolina-Automatico-Prata-2019-Porsche-Lateral-Frente-Lado-Esquerdo-Prime-Veiculos-BH-Belo-Horizonte-MG.jpeg",
        isGoodBuy: false,
        isActive: true,
        isHomePage: true,
        isLarge: false,
      },
      {
        id: "10",
        title: "Porsche - 718",
        description: "Product title stays here - maximum 1 line",
        owner: "Christian",
        km: "0",
        year: "2019",
        price: "00.000,00",
        image:
          "https://primeveiculosbh.com.br/wp-content/uploads/2023/01/718-Cayman-2.0-Turbo-Gasolina-Automatico-Prata-2019-Porsche-Lateral-Frente-Lado-Esquerdo-Prime-Veiculos-BH-Belo-Horizonte-MG.jpeg",
        isGoodBuy: false,
        isActive: true,
        isHomePage: true,
        isLarge: false,
      },
      {
        id: "11",
        title: "Porsche - 718",
        description: "Product title stays here - maximum 1 line",
        owner: "Christian",
        km: "0",
        year: "2019",
        price: "00.000,00",
        image:
          "https://primeveiculosbh.com.br/wp-content/uploads/2023/01/718-Cayman-2.0-Turbo-Gasolina-Automatico-Prata-2019-Porsche-Lateral-Frente-Lado-Esquerdo-Prime-Veiculos-BH-Belo-Horizonte-MG.jpeg",
        isGoodBuy: false,
        isActive: true,
        isHomePage: true,
        isLarge: false,
      },
      {
        id: "12",
        title: "Porsche - 718",
        description: "Product title stays here - maximum 1 line",
        owner: "Christian",
        km: "0",
        year: "2019",
        price: "00.000,00",
        image:
          "https://primeveiculosbh.com.br/wp-content/uploads/2023/01/718-Cayman-2.0-Turbo-Gasolina-Automatico-Prata-2019-Porsche-Lateral-Frente-Lado-Esquerdo-Prime-Veiculos-BH-Belo-Horizonte-MG.jpeg",
        isGoodBuy: false,
        isActive: true,
        isHomePage: true,
        isLarge: false,
      },
  ]